version: "2"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.base
    command: yarn api-dev
    volumes:
      - .:/home/app/chorus
    ports:
      - 3000:3000

  www:
    build:
      context: .
      dockerfile: docker/Dockerfile.base
    command: yarn www-dev
    volumes:
      - .:/home/app/chorus
    ports:
      - 8080:8080